/* This file is generated by scripts/generate-certificates.mjs. Do not edit manually. */

export type CertificateAsset = {
  id: string;
  title: string;
  category: string;
  organisation: string;
  src: string;
  type: "image" | "pdf";
};

export const certificateAssets: CertificateAsset[] = [
  {
    "id": "certificates-certificates-achievements-kasakranthikiran-3024-microsoft-learn-pdf",
    "title": "Achievements kasakranthikiran 3024 Microsoft Learn",
    "category": "Certifications",
    "organisation": "Microsoft Learn",
    "src": "/assets/certificates/CERTIFICATES/Achievements%20-%20kasakranthikiran-3024%20_%20Microsoft%20Learn.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-certificates-campus-ambassador-kitech-pdf",
    "title": "CAMPUS AMBASSADOR KITECH",
    "category": "Certifications",
    "organisation": "Kitech",
    "src": "/assets/certificates/CERTIFICATES/CAMPUS%20AMBASSADOR%20KITECH.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-certificates-campus-ambassador-skill-intern-pdf",
    "title": "CAMPUS AMBASSADOR SKILL INTERN",
    "category": "Certifications",
    "organisation": "Professional learning",
    "src": "/assets/certificates/CERTIFICATES/CAMPUS%20AMBASSADOR%20SKILL%20INTERN.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-ai-hp-pdf",
    "title": "ai hp",
    "category": "Courses",
    "organisation": "Professional learning",
    "src": "/assets/certificates/COURCES/ai%20hp.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-analytics-vidhya-deep-seek-pdf",
    "title": "ANALYTICS VIDHYA DEEP SEEK",
    "category": "Courses",
    "organisation": "Analytics Vidhya",
    "src": "/assets/certificates/COURCES/ANALYTICS%20VIDHYA%20DEEP%20SEEK.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-deloitte-data-analytics-job-simulation-pdf",
    "title": "Deloitte Data Analytics Job Simulation",
    "category": "Courses",
    "organisation": "Deloitte",
    "src": "/assets/certificates/COURCES/Deloitte%20Data%20Analytics%20Job%20Simulation.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-geeksforgeeks-mongodb-pdf",
    "title": "GeeksforGeeks MongoDB",
    "category": "Courses",
    "organisation": "GeeksforGeeks",
    "src": "/assets/certificates/COURCES/GeeksforGeeks%20MongoDB.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-ibm-ai-fundamentals-pdf",
    "title": "IBM AI FUNDAMENTALS",
    "category": "Courses",
    "organisation": "IBM",
    "src": "/assets/certificates/COURCES/IBM%20AI%20FUNDAMENTALS.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-ibm-dev-skill-netwok-prompt-engineering-for-everyone-pdf",
    "title": "IBM DEV SKILL NETWOK PROMPT ENGINEERING FOR EVERYONE",
    "category": "Courses",
    "organisation": "IBM",
    "src": "/assets/certificates/COURCES/IBM%20DEV%20SKILL%20NETWOK%20PROMPT%20ENGINEERING%20FOR%20EVERYONE.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-ibm-introduction-to-quantum-computing-pdf",
    "title": "IBM INTRODUCTION TO QUANTUM COMPUTING",
    "category": "Courses",
    "organisation": "IBM",
    "src": "/assets/certificates/COURCES/IBM%20INTRODUCTION%20TO%20QUANTUM%20COMPUTING.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-introduction-to-generative-ai-skillsbuild-pdf",
    "title": "INTRODUCTION TO GENERATIVE AI SkillsBuild",
    "category": "Courses",
    "organisation": "SkillsBuild",
    "src": "/assets/certificates/COURCES/INTRODUCTION%20TO%20GENERATIVE%20AI%20_%20SkillsBuild.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-power-bi-kasa-kranthi-cr920-certificate-pdf",
    "title": "Kasa Kranthi CR920 certificate",
    "category": "Courses",
    "organisation": "Professional learning",
    "src": "/assets/certificates/COURCES/power%20bi/Kasa%20Kranthi_CR920_certificate.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-power-bi-quiz-result-pdf",
    "title": "quiz result",
    "category": "Courses",
    "organisation": "Professional learning",
    "src": "/assets/certificates/COURCES/power%20bi/quiz_result.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-simplelearn-introduction-to-artificial-intelligence-pdf",
    "title": "SimpleLearn Introduction to Artificial Intelligence",
    "category": "Courses",
    "organisation": "SimpleLearn",
    "src": "/assets/certificates/COURCES/SimpleLearn%20Introduction%20to%20Artificial%20Intelligence.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-simplilearn-google-cloud-introduction-to-generative-ai-pdf",
    "title": "Simplilearn google cloud Introduction to Generative AI",
    "category": "Courses",
    "organisation": "Simplilearn",
    "src": "/assets/certificates/COURCES/Simplilearn%20google%20cloud%20Introduction%20to%20Generative%20AI.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-cources-simplilearn-power-bi-pdf",
    "title": "Simplilearn POWER BI",
    "category": "Courses",
    "organisation": "Simplilearn",
    "src": "/assets/certificates/COURCES/Simplilearn%20POWER%20BI.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-internships-edvedha-python-intern-pdf",
    "title": "EDVEDHA PYTHON INTERN",
    "category": "Internships",
    "organisation": "Edvedha",
    "src": "/assets/certificates/INTERNSHIPS/EDVEDHA%20PYTHON%20INTERN.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-internships-yuga-yatra-internship-certificate-png",
    "title": "Yuga Yatra Internship Certificate",
    "category": "Internships",
    "organisation": "Yuga Yatra",
    "src": "/assets/certificates/INTERNSHIPS/Yuga%20Yatra%20Internship%20Certificate.png",
    "type": "image"
  },
  {
    "id": "certificates-webniar-full-hcl-guvicertification-2fj307idl396455xp1-full-stack-png",
    "title": "GuviCertification 2FJ307IDl396455XP1(full stack)",
    "category": "Webinars",
    "organisation": "GUVI",
    "src": "/assets/certificates/WEBNIAR/full%20hcl/GuviCertification%20-%202FJ307IDl396455XP1(full%20stack).png",
    "type": "image"
  },
  {
    "id": "certificates-webniar-al-hcl-guvicertification-80c2h36157z95i5op7-png",
    "title": "GuviCertification 80C2H36157z95I5oP7",
    "category": "Webinars",
    "organisation": "GUVI",
    "src": "/assets/certificates/WEBNIAR/AL%20HCL/GuviCertification%20-%2080C2H36157z95I5oP7.png",
    "type": "image"
  },
  {
    "id": "certificates-webniar-guvicertification-data-science-png",
    "title": "GuviCertification data science",
    "category": "Webinars",
    "organisation": "GUVI",
    "src": "/assets/certificates/WEBNIAR/GuviCertification%20data%20science.png",
    "type": "image"
  },
  {
    "id": "certificates-webniar-guvicertification-full-stack-skills-that-crack-product-based-companies-png",
    "title": "GuviCertification Full Stack Skills That Crack Product Based Companies",
    "category": "Webinars",
    "organisation": "GUVI",
    "src": "/assets/certificates/WEBNIAR/GuviCertification%20-%20Full%20Stack%20Skills%20That%20Crack%20Product-Based%20Companies.png",
    "type": "image"
  },
  {
    "id": "certificates-webniar-scaler-roadtoai-png",
    "title": "SCALER ROADTOAI",
    "category": "Webinars",
    "organisation": "Scaler",
    "src": "/assets/certificates/WEBNIAR/SCALER%20ROADTOAI.png",
    "type": "image"
  },
  {
    "id": "certificates-workshops-ewayte-on-professional-career-pdf",
    "title": "EWAYTE ON PROFESSIONAL CAREER",
    "category": "Workshops",
    "organisation": "Ewayte",
    "src": "/assets/certificates/WORKSHOPS/EWAYTE%20ON%20PROFESSIONAL%20CAREER.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-workshops-national-lv-short-term-training-2k24-srec-brain-o-vision-on-java-full-stack-with-react-js-ai-pdf",
    "title": "NATIONAL LV SHORT TERM TRAINING 2K24 SREC BRAIN O VISION ON JAVA FULL STACK WITH REACT JS & AI",
    "category": "Workshops",
    "organisation": "SREC",
    "src": "/assets/certificates/WORKSHOPS/NATIONAL%20LV%20SHORT%20TERM%20TRAINING%202K24%20SREC%20BRAIN%20O%20VISION%20ON%20JAVA%20FULL%20STACK%20WITH%20REACT%20JS%20%26%20AI.pdf",
    "type": "pdf"
  },
  {
    "id": "certificates-workshops-prompt-eng-pantech-participation-certificate-pdf",
    "title": "PROMPT ENG PANTECH Participation certificate",
    "category": "Workshops",
    "organisation": "Pantech",
    "src": "/assets/certificates/WORKSHOPS/PROMPT%20ENG%20PANTECH%20Participation%20certificate.pdf",
    "type": "pdf"
  }
];
